id: 21
name: ReleaseSieveFunction
type: patch/major/minor
functions:
  - name: sieve
    base_version:
      path: fns/sample_f1
      env: nodejs
    new_version:
      path: fns/sample_f2
      env: nodejs
stages:
  - name: Canary test sieve
    type: WaitForSignal # TODO modify?
    func_name: sieve
    variants:
      - name: base_version
        trafficPercentage: 90
      - name: new_version
        trafficPercentage: 10 # can't be changed after proxy deployment
    metrics_conditions: # AND condition
      - name: errorRate
        threshold: "<0.02"
      - name: responseTime
        threshold: "<=200"
        compareWith: "Median"
    end_conditions: # NOTE: not considered by WaitForSignal type
      - name: minDuration
        threshold: 10s
      - name: minCalls
        threshold: "10"
    end_action:
      onSuccess: A/B Test Sieve
      onFailure: rollback
  - name: A/B Test Sieve
    type: A/B
    func_name: sieve
    variants:
      - name: base_version
        trafficPercentage: 50
      - name: new_version
        trafficPercentage: 50 # can't be changed after proxy deployment
    metrics_conditions: # AND condition
      - name: errorRate
        threshold: "<0.02"
      - name: responseTime
        threshold: "<=200"
        compareWith: "Median"
    end_conditions:
      - name: minDuration
        threshold: 10s
      - name: minCalls
        threshold: "10"
    end_action:
      onSuccess: rollout
      onFailure: rollback
rollback:
  action:
    function: base_version